// Code generated by protoc-gen-go-hz.

package main

import (
	handler "github.com/ca-x/protoc-gen-go-hz/example/biz/handler"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizedRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
}
