// Code generated by protoc-gen-go-hz. DO NOT EDIT.

package main

import (
	router "github.com/ca-x/protoc-gen-go-hz/example/biz/router"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// register registers all routers.
func register(r *server.Hertz) {
	router.GeneratedRegister(r)
	customizedRegister(r)
}
