// Code generated by protoc-gen-go-hz v0.9.8. DO NOT EDIT.

package router

import (
	"github.com/ca-x/protoc-gen-go-hz/example/biz/handler"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// Register registers HTTP handlers.
func Register(r *server.Hertz) {
	r.POST("/Greeter/SayHello", handler.SayHello)
	r.POST("/Greeter/SayGoodbye", handler.SayGoodbye)
}
