// Code generated by protoc-gen-go-hz v0.9.8. DO NOT EDIT.

package handler

import (
	"context"
	"github.com/ca-x/protoc-gen-go-hz/example/biz/model"
	"github.com/cloudwego/hertz/pkg/app"
)

// SayGoodbye .
func SayGoodbye(ctx context.Context, c *app.RequestContext) {
	var err error
	var req model.HelloRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(400, map[string]interface{}{
			"error": err.Error(),
		})
		return
	}

	// TODO: implement your business logic here
	resp := &model.HelloReply{}
	c.JSON(200, resp)
}
