// Code generated by protoc-gen-hz. DO NOT EDIT.

package handler

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/example/project/biz/model"
)

// SayHello .
func SayHello(ctx context.Context, c *app.RequestContext) {
	var err error
	var req model.HelloRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(400, map[string]interface{}{
			"error": err.Error(),
		})
		return
	}

	// TODO: implement your business logic here
	resp := &model.HelloReply{}
	c.JSON(200, resp)
}
