// Code generated by protoc-gen-hz. DO NOT EDIT.
// versions:
//     protoc-gen-go v1.31.0
//     protoc        v3.21.0
// source: example.proto

package model

import (
    protoreflect "google.golang.org/protobuf/reflect/protoreflect"
    protoimpl "google.golang.org/protobuf/runtime/protoimpl"
    reflect "reflect"
    sync "sync"
)

const (
    // Verify that this generated code is sufficiently up-to-date.
    _ = protoimpl.EnforceVersion(20 - 0)
    // Verify that runtime/protoimpl is sufficiently up-to-date.
    _ = protoimpl.EnforceVersion(34 - 20)
)

type HelloRequest struct {
    Name string `name:`
    Age  int32  `age:`
}

func (x *HelloRequest) Reset() {
    *x = HelloRequest{}
}

func (x *HelloRequest) String() string {
    return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) Descriptor() protoreflect.MessageDescriptor {
    return file_HelloRequest_proto.MsgTypes()[0].Descriptor()
}

type HelloReply struct {
    Message string `message:`
    Code    int32  `code:`
}

func (x *HelloReply) Reset() {
    *x = HelloReply{}
}

func (x *HelloReply) String() string {
    return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) Descriptor() protoreflect.MessageDescriptor {
    return file_HelloReply_proto.MsgTypes()[0].Descriptor()
}
