// Code generated by protoc-gen-go-hz. DO NOT EDIT.

package router

import (
    "github.com/cloudwego/hertz/pkg/app/server"
    "github.com/example/project/biz/handler"
)

// Register registers HTTP handlers.
func Register(r *server.Hertz) {
    r.POST("/Greeter/SayHello", handler.SayHello)
    r.POST("/Greeter/SayGoodbye", handler.SayGoodbye)
}
